title: Rizentium
logo: /assets/img/logo.png
description: Hi, I'm Software Developer that have little bit sense of art to make the code clear and clean.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
